export const SharedStyles = {
    "font": "System",
    "headerSize": 65,
    "subheaderSize": 50,
    "textSize": 28,
    "subTextSize": 17,
    "btnTextSize": 13,
    "inputTextSize": 15,
    "headerColor": "#000000",
    "subheaderColor": "#000000",
    "textColor": "#000000",
    "subTextColor": "#000000",
    "inputTextColor": "#000000",
    "headerPosition": "center",
    "leftPageMarginPercent": 5,
    "rightPageMarginPercent": 5,
    "topPageMargin": 45,
    "elementSpacing": 12,
    "logoTintColor": "#de2346"
};